name: acs_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  provider: ^6.0.2
  email_validator: ^2.1.17
  flutter_pw_validator: ^1.5.0
  cloud_firestore: ^4.4.5
  password_strength: ^0.2.0
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/index.html
  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
